name: infra
description: infra package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  dio: ^4.0.0

  core:
    path: ../core

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  test: ^1.17.10